#############################################################################
# The MIT License (MIT)                                                     #
#                                                                           #
# Copyright 2017 papa.                                                      #
#                                                                           #
# Permission is hereby granted, free of charge, to any person obtaining     #
# a copy of this software and associated documentation files  to deal       #
# (the “Software”), in the Software without restriction, including          #
# without limitation the rights to use, copy, modify, merge, publish,       #
# distribute, sublicense, and/or sell copies of the Software, and to permit #
# persons to whom the Software is furnished to do so, subject to the        #
# following conditions:                                                     #
#                                                                           #
# The above copyright notice and this permission notice shall be included   #
# in all copies or substantial portions of the Software.                    #
#                                                                           #
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS   #
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF                #
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.    #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR          #
# ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,  #
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE         #
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                    #
#############################################################################

# this playbook installs couchdb.
---

- name: Install couchdb
  sudo: True
  hosts: db
  vars_files:
    - ../common/vars.yml
  vars: 
    
  tasks:

    - name: Install nvm
      shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash

    - name: Install nodejs
      shell: nvm install 6.11.0

    - name: Install Sphinx
      shell: pip install Sphinx

    - stat: path={{ dev_dir }}
      register: dev_dir_exists

    - name: Create a dev repo directory
      file: path={{ dev_dir }} state=directory mode=0755 owner={{ ansible_user }}
      when: dev_dir_exists.stat.isdir is not defined or dev_dir_exists.stat.isdir == False

    - stat: path={{ dev_dir}}/couchdb
      register: kub_dir_exists

    - name: Download couchdb
      git: repo="{{ couchdb_url }}" dest="{{ dev_dir }}" clone=yes update=yes
      when: kub_dir_exists.stat.isdir is not defined or kub_dir_exists.stat.isdir == False

    - name: Configure and build couchdb
      git: cd "{{ dev_dir }}/couchdb" && ./configure && make release

    - name: Run couchdb 
      copy: src="{{ dev_dir }}/couchdb/rel/couchdb" dest="{{ user_local_lib }}" directory_mode=yes
